server:
  port: 8081

spring:
  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal

vitordev:
  client:
    address:
      url: http://localhost:8082/addresses